### ISSUE TITLE
Problems Running the build-pdf.sh Script

### ISSUE THREAD

**Issue by amckinnell** [gratiartis/diagrams-as-code#2]
To get the `build-pdf.sh` script to run from the command line I first had to run `bundle binstubs asciidoctor` to create a bin stub for the `asciidoctor` executable in the `/bin` directory.

Nice example. Thanks for creating it.

**Comment by stephen-masters** [comment]
You did? I didn't need to do that for some reason. I can see it in my `/usr/local/lib/ruby/gems/3.0.0/bin`, so maybe I did it for a previous project and forgot.

Thank you for the tip - I have added a note to `README.md`
