### ISSUE TITLE
`./build-pdf.sh` fails: `asciidoctor: FAILED: 'asciidoctor-diagram' could not be loaded`

### ISSUE THREAD

**Issue by nicokosi** [gratiartis/diagrams-as-code#3]
Hello,

I cannot build the PDF this way: 

```sh
$ uname -srv
Linux 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021

$ asciidoctor --version
Asciidoctor 2.0.15 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

$ ./build-pdf.sh
asciidoctor: FAILED: 'asciidoctor-diagram' could not be loaded
  Use --trace for backtrace
```

Note than I did various things before: :nerd_face: 
```sh
$ history
5732  brew install graphviz
5734  brew install asciidoctor
5743  brew install asciidoctor-diagram
5746  npm install
5748  bundle
5773  bundle binstubs asciidoctor
```

Any tip/recommendation? (_RTFM!_, maybe?! :wink:)

**Comment by stephen-masters** [comment]
Hi Nicolas. Sorry you had trouble with that.

I'll test it out on Ubuntu - I've run all this stuff in an Ubuntu Docker container in the past.

Apart from Ubuntu, I'm thinking maybe it's connected to installing asciidoctor and asciidoctor-diagram 2 ways? The `bundle` command should install it via Ruby Gems, so I don't have it via homebrew.

In terms of versions I'm as follows:

```
% ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]

% asciidoctor --version
Asciidoctor 2.0.15 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by stephen-masters** [comment]
To get around issues relating to specific operating systems, I've created a `Dockerfile` and `docker-compose.yml`, which create a working environment. Info on how to run it can be found in `README.md`.

**Comment by nicokosi** [comment]
Thank you @gratiartis. :+1: 
I have just created a new issue: #4. :innocent:
